version: '3'

services:
  web:
    build: .
    volumes:
      - ./app:/usr/src/app
      - ./frontend/build:/usr/src/app/frontend/build
    ports:
      - "8000:8000"
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/self-signed.crt:/etc/nginx/certs/self-signed.crt
      - ./nginx/self-signed.key:/etc/nginx/certs/self-signed.key
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - web
